server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/thinkmaldb?serverTimezone=UTC
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.nk: debug
