server:
  port:  9999

spring:
  application:
    name: content-api
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/thinkmaldb?serverTimezone=UTC

logging:
  level:
    com.example:  debug
